micronaut:
  application:
    name: clientService

datasources:
  default:
    url: jdbc:mysql://localhost:3306/clientes-db
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    packages-to-scan:
      - 'br.com.curso.udemy.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

netty:
  default:
    allocator:
      max-order: 3