micronaut:
  application:
    name: clientService

# conexão com banco de dados MySQL local
datasources:
  default:
    url: jdbc:mysql://localhost:3306/clientes-db
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
    # schema-generate: CREATE_DROP
    dialect: MYSQL

# definição de estratégia para criação de tabelas com JPA
jpa:
  default:
    packages-to-scan:
      - 'br.com.curso.udemy.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

netty:
  default:
    allocator:
      max-order: 3